# Generated by Django 4.1.4 on 2022-12-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=270)),
                ('authors', models.CharField(max_length=110)),
                ('publishedDate', models.CharField(max_length=10)),
                ('pageCount', models.IntegerField()),
                ('thumbnail', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=10)),
            ],
        ),
    ]
