# Generated by Django 4.1.4 on 2022-12-18 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='pageCount',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishedDate',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['ISBN'], name='main_book_ISBN_01cf3f_idx'),
        ),
    ]
