# Generated by Django 4.1.4 on 2023-01-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cost',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
