# Generated by Django 4.1.4 on 2023-01-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_book_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="ISBN",
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name="book",
            constraint=models.UniqueConstraint(fields=("user", "ISBN"), name="unique book assigment for user"),
        ),
    ]
