# Generated by Django 4.1.4 on 2023-01-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_book_isbn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="ISBN",
            field=models.BigIntegerField(),
        ),
    ]
