# Generated by Django 4.1.4 on 2023-01-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_book_isbn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="authors",
            field=models.CharField(blank=True, default=None, max_length=110, null=True),
        ),
    ]
